import './globals.css'
import type { Metadata } from 'next'
import { Inter, Sora } from 'next/font/google'
import Layout from '@/components/Layout';
import "@fontsource/inter";
import "@fontsource/inter/900.css";
import "@fontsource/inter/700.css";

const inter = Inter({ subsets: ['latin'] })
const sora = Sora({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={sora.className}><Layout>{children}</Layout></body>
    </html>
  )
}
